smallMonsters = [
    {'name': 'Anteka', 'size': 'small'},
    {'name': 'Apceros', 'size': 'small'},
    {'name': 'Aptonoth', 'size': 'small'},
    {'name': 'Barnos', 'size': 'small'},
    {'name': 'Boaboa', 'size': 'small'},
    {'name': 'Cortos', 'size': 'small'},
    {'name': 'Gajalaka', 'size': 'small'},
    {'name': 'Gajau', 'size': 'small'}, {'name': 'Gastodon', 'size': 'small'}, {'name': 'Girros', 'size': 'small'}, {'name': 'Grimalkyne', 'size': 'small'}, {'name': 'Hornetaur', 'size': 'small'}, {'name': 'Jagras', 'size': 'small'}, {'name': 'Kelbi', 'size': 'small'}, {'name': 'Kestodon', 'size': 'small'}, {'name': 'Mernos', 'size': 'small'}, {'name': 'Mosswine', 'size': 'small'}, {'name': 'Noios', 'size': 'small'}, {'name': 'Popo', 'size': 'small'}, {'name': 'Raphinos', 'size': 'small'}, {'name': 'Shamos', 'size': 'small'}, {'name': 'Vespoid', 'size': 'small'}, {'name': 'Wulg', 'size': 'small'}]

locales = [
    ('Ancient Forest',),
    ('Wildspire Wastes',),
    ('Coral Highlands',),
    ('Rotten Vale',),
    ('Elder\'s Recess',),
    ('Hoarfrost Reach',),
    ('Secluded Valley',),
    ('Guiding Lands',),
    ('Castle Schrade',),
    ('Caverns of El Dorado',),
]

# largeMonsters = [{'name': 'Acidic Glavenus', 'type': 'Brute Wyvern', 'size': 'large', 'locales': []}, {'name': 'Alatreon', 'type': 'Elder Dragon', 'size': 'large', 'locales': []}, {'name': 'Ancient Leshen', 'type': 'Relict', 'size': 'large', 'locales': []}, {'name': 'Anjanath', 'type': 'Brute Wyvern', 'size': 'large', 'locales': []}, {'name': 'Azure Rathalos', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []}, {'name': 'Banbaro', 'type': 'Brute Wyvern', 'size': 'large', 'locales': []}, {'name': 'Barioth', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []}, {'name': 'Barroth', 'type': 'Brute Wyvern', 'size': 'large', 'locales': []}, {'name': 'Bazelgeuse', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []}, {'name': 'Behemoth', 'type': 'Elder Dragon', 'size': 'large', 'locales': []}, {'name': 'Beotodus', 'type': 'Piscine Wyvern', 'size': 'large', 'locales': []}, {'name': 'Black Diablos', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []}, {'name': 'Blackveil Vaal Hazak', 'type': 'Elder Dragon', 'size': 'large', 'locales': []}, {'name': 'Brachydios', 'type': 'Brute Wyvern', 'size': 'large', 'locales': []}, {'name': 'Brute Tigrex', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []}, {'name': 'Coral Pukei-Pukei', 'type': 'Bird Wyvern', 'size': 'large', 'locales': []}, {'name': 'Deviljho', 'type': 'Brute Wyvern', 'size': 'large', 'locales': []}, {'name': 'Diablos', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []}, {'name': 'Dodogama', 'type': 'Fanged Wyvern', 'size': 'large', 'locales': []}, {'name': 'Ebony Odogaron', 'type': 'Fanged Wyvern', 'size': 'large', 'locales': []}, {'name': 'Fatalis', 'type': 'Elder Dragon', 'size': 'large', 'locales': []}, {'name': 'Frostfang Barioth', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []}, {'name': 'Fulgar Anjanath', 'type': 'Brute Wyvern', 'size': 'large', 'locales': []}, {'name': 'Furious Rajang', 'type': 'Fanged Beast', 'size': 'large', 'locales': []}, {'name': 'Glavenus', 'type': 'Brute Wyvern', 'size': 'large', 'locales': []}, {'name': 'Gold Rathian', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []}, {'name': 'Great Girros', 'type': 'Fanged Wyvern', 'size': 'large', 'locales': []}, {'name': 'Great Jagras', 'type': 'Fanged Wyvern', 'size': 'large', 'locales': []}, {'name': 'Jyuratodos', 'type': 'Piscine Wyvern', 'size': 'large', 'locales': []}, {'name': 'Kirin', 'type': 'Elder Dragon', 'size': 'large', 'locales': []}, {'name': 'Kulu-Ya-Ku', 'type': 'Bird Wyvern', 'size': 'large', 'locales': []}, {'name': 'Kulve Taroth', 'type': 'Elder Dragon', 'size': 'large', 'locales': []}, {'name': 'Kushala Daora', 'type': 'Elder Dragon', 'size': 'large', 'locales': []}, {'name': 'Lavasioth', 'type': 'Piscine Wyvern', 'size': 'large', 'locales': []}, {'name': 'Legiana', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []}, {'name': 'Leshen', 'type': 'Relict', 'size': 'large', 'locales': []}, {'name': 'Lunastra', 'type': 'Elder Dragon', 'size': 'large', 'locales': []}, {'name': 'Namielle', 'type': 'Elder Dragon', 'size': 'large', 'locales': []}, {'name': 'Nargacuga', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []}, {'name': 'Nergigante', 'type': 'Elder Dragon', 'size': 'large', 'locales': []}, {'name': 'Nightshade Paolumu', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []}, {'name': 'Odogaron', 'type': 'Fanged Wyvern', 'size': 'large', 'locales': []}, {'name': 'Paolumu', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []}, {'name': 'Pink Rathian', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []}, {'name': 'Pukei-Pukei', 'type': 'Bird Wyvern', 'size': 'large', 'locales': []}, {'name': 'Radobaan', 'type': 'Brute Wyvern', 'size': 'large', 'locales': []}, {'name': 'Raging Brachydios', 'type': 'Brute Wyvern', 'size': 'large', 'locales': []}, {'name': 'Rajang', 'type': 'Fanged Beast', 'size': 'large', 'locales': []}, {'name': 'Ratholos', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []}, {'name': 'Rathian', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []}, {'name': 'Ruiner Nergigante', 'type': 'Elder Dragon', 'size': 'large', 'locales': []}, {'name': "Safi'jiiva", 'type': 'Elder Dragon', 'size': 'large', 'locales': []}, {'name': 'Savage Deviljho', 'type': 'Brute Wyvern', 'size': 'large', 'locales': []}, {'name': 'Scarred Yian Garuga', 'type': 'Bird Wyvern', 'size': 'large', 'locales': []}, {'name': 'Seething Bazelgeuse', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []}, {'name': 'Shara Ishvalda', 'type': 'Elder Dragon', 'size': 'large', 'locales': []}, {'name': 'Shrieking Legiana', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []}, {'name': 'Silver Rathalos', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []}, {'name': 'Stygian Zinogre', 'type': 'Fanged Wyvern', 'size': 'large', 'locales': []}, {'name': 'Teostra', 'type': 'Elder Dragon', 'size': 'large', 'locales': []}, {'name': 'Tigrex', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []}, {'name': 'Tobi-Kadachi', 'type': 'Fanged Wyvern', 'size': 'large', 'locales': []}, {'name': 'Tziti-Ya-Ku', 'type': 'Bird Wyvern', 'size': 'large', 'locales': []}, {'name': 'Urugaan', 'type': 'Brute Wyvern', 'size': 'large', 'locales': []}, {'name': 'Vaal Hazak', 'type': 'Elder Dragon', 'size': 'large', 'locales': []}, {'name': 'Velkhana', 'type': 'Elder Dragon', 'size': 'large', 'locales': []}, {'name': 'Viper Tobi-Kadachi', 'type': 'Fanged Wyvern', 'size': 'large', 'locales': []}, {'name': 'Xenojiva', 'type': 'Elder Dragon', 'size': 'large', 'locales': []}, {'name': 'Yian Garuga', 'type': 'Bird Wyvern', 'size': 'large', 'locales': []}, {'name': 'Zinogre', 'type': 'Fanged Wyvern', 'size': 'large', 'locales': []}, {'name': 'Zorah Magdaros', 'type': 'Elder Dragon', 'size': 'large', 'locales': []}]
largeMonsters = [
{'name': 'Acidic Glavenus', 'type': 'Brute Wyvern', 'size': 'large', 'locales': ['Rotten Vale']},
{'name': 'Alatreon', 'type': 'Elder Dragon', 'size': 'large', 'locales': ['Secluded Valley']},
{'name': 'Ancient Leshen', 'type': 'Relict', 'size': 'large', 'locales': ['Ancient Forest']},
{'name': 'Anjanath', 'type': 'Brute Wyvern', 'size': 'large', 'locales': ['Ancient Forest', 'Wildspire Waste']},
{'name': 'Azure Rathalos', 'type': 'Flying Wyvern', 'size': 'large', 'locales': ['Ancient Forest', 'Elder\'s Recess']},
{'name': 'Banbaro', 'type': 'Brute Wyvern', 'size': 'large', 'locales': ['Ancient Forest','Wildspire Wastes','Coral Highlands','Rotten Vale','Elder\'s Recess','Hoarfrost Reach']},
{'name': 'Barioth', 'type': 'Flying Wyvern', 'size': 'large', 'locales': ['Hoarfrost Reach']},
{'name': 'Barroth', 'type': 'Brute Wyvern', 'size': 'large', 'locales': ['Wildspire Waste']},
{'name': 'Bazelgeuse', 'type': 'Flying Wyvern', 'size': 'large', 'locales': ['Ancient Forest','Wildspire Wastes','Coral Highlands','Rotten Vale','Elder\'s Recess']},
{'name': 'Behemoth', 'type': 'Elder Dragon', 'size': 'large', 'locales': ['Elder\'s Recess']},
{'name': 'Beotodus', 'type': 'Piscine Wyvern', 'size': 'large', 'locales': ['Hoarfrost Reach']},
{'name': 'Black Diablos', 'type': 'Flying Wyvern', 'size': 'large', 'locales': ['Wildspire Waste']},
{'name': 'Blackveil Vaal Hazak', 'type': 'Elder Dragon', 'size': 'large', 'locales': ['Ancient Forest', 'Rotten Vale']},
{'name': 'Brachydios', 'type': 'Brute Wyvern', 'size': 'large', 'locales': ['Elder\'s Recess']},
{'name': 'Brute Tigrex', 'type': 'Flying Wyvern', 'size': 'large', 'locales': ['Guiding Lands']},
{'name': 'Coral Pukei-Pukei', 'type': 'Bird Wyvern', 'size': 'large', 'locales': ['Coral Highlands']},
{'name': 'Deviljho', 'type': 'Brute Wyvern', 'size': 'large', 'locales': ['Ancient Forest','Wildspire Wastes','Coral Highlands','Rotten Vale','Elder\'s Recess','Hoarfrost Reach']},
{'name': 'Diablos', 'type': 'Flying Wyvern', 'size': 'large', 'locales': ['Wildspire Waste']},
{'name': 'Dodogama', 'type': 'Fanged Wyvern', 'size': 'large', 'locales': ['Elder\'s Recess']},
{'name': 'Ebony Odogaron', 'type': 'Fanged Wyvern', 'size': 'large', 'locales': ['Ancient Forest','Wildspire Wastes','Coral Highlands','Rotten Vale','Elder\'s Recess','Hoarfrost Reach']},
{'name': 'Fatalis', 'type': 'Elder Dragon', 'size': 'large', 'locales': ['Castle Schrade']},
{'name': 'Frostfang Barioth', 'type': 'Flying Wyvern', 'size': 'large', 'locales': ['Hoarfrost Reach']},
{'name': 'Fulgar Anjanath', 'type': 'Brute Wyvern', 'size': 'large', 'locales': ['Ancient Forest','Wildspire Wastes','Coral Highlands','Rotten Vale','Elder\'s Recess','Hoarfrost Reach']},
{'name': 'Furious Rajang', 'type': 'Fanged Beast', 'size': 'large', 'locales': ['Hoarfrost Reach']},
{'name': 'Glavenus', 'type': 'Brute Wyvern', 'size': 'large', 'locales': ['Ancient Forest', 'Wildspire Waste', 'Elder\'s Recess']},
{'name': 'Gold Rathian', 'type': 'Flying Wyvern', 'size': 'large', 'locales': ['Guiding Lands']},
{'name': 'Great Girros', 'type': 'Fanged Wyvern', 'size': 'large', 'locales': ['Rotten Vale']},
{'name': 'Great Jagras', 'type': 'Fanged Wyvern', 'size': 'large', 'locales': ['Ancient Forest']},
{'name': 'Jyuratodos', 'type': 'Piscine Wyvern', 'size': 'large', 'locales': ['Wildspire Waste']},
{'name': 'Kirin', 'type': 'Elder Dragon', 'size': 'large', 'locales': ['Coral Highlands']},
{'name': 'Kulu-Ya-Ku', 'type': 'Bird Wyvern', 'size': 'large', 'locales': ['Ancient Forest', 'Wildspire Waste']},
{'name': 'Kulve Taroth', 'type': 'Elder Dragon', 'size': 'large', 'locales': ['Caverns of El Dorado']},
{'name': 'Kushala Daora', 'type': 'Elder Dragon', 'size': 'large', 'locales': ['Ancient Forest', 'Elder\'s Recess']},
{'name': 'Lavasioth', 'type': 'Piscine Wyvern', 'size': 'large', 'locales': ['Elder\'s Recess']},
{'name': 'Legiana', 'type': 'Flying Wyvern', 'size': 'large', 'locales': ['Coral Highlands','Rotten Vale','Hoarfrost Reach']},
{'name': 'Leshen', 'type': 'Relict', 'size': 'large', 'locales': ['Ancient Forest']},
{'name': 'Lunastra', 'type': 'Elder Dragon', 'size': 'large', 'locales': ['Wildspire Wastes', 'Elder\'s Recess']},
{'name': 'Namielle', 'type': 'Elder Dragon', 'size': 'large', 'locales': ['Coral Highlands']},
{'name': 'Nargacuga', 'type': 'Flying Wyvern', 'size': 'large', 'locales': ['Ancient Forest', 'Coral Highlands']},
{'name': 'Nergigante', 'type': 'Elder Dragon', 'size': 'large', 'locales': ['Wilspire Waste', 'Elder\'s Recess']},
{'name': 'Nightshade Paolumu', 'type': 'Flying Wyvern', 'size': 'large', 'locales': ['Wildspire Waste', 'Ancient Forest']},
{'name': 'Odogaron', 'type': 'Fanged Wyvern', 'size': 'large', 'locales': ['Coral Highlands', 'Rotten Vale']},
{'name': 'Paolumu', 'type': 'Flying Wyvern', 'size': 'large', 'locales': ['Coral Highlands']},
{'name': 'Pink Rathian', 'type': 'Flying Wyvern', 'size': 'large', 'locales': ['Wildspire Waste', 'Coral Highlands']},
{'name': 'Pukei-Pukei', 'type': 'Bird Wyvern', 'size': 'large', 'locales': ['Ancient Forest', 'Wildspire Waste']},
{'name': 'Radobaan', 'type': 'Brute Wyvern', 'size': 'large', 'locales': ['Rotten Vale']},
{'name': 'Raging Brachydios', 'type': 'Brute Wyvern', 'size': 'large', 'locales': ['Guiding Lands']},
{'name': 'Rajang', 'type': 'Fanged Beast', 'size': 'large', 'locales': ['Guilding Lands']},
{'name': 'Rathalos', 'type': 'Flying Wyvern', 'size': 'large', 'locales': ['Ancient Forest']},
{'name': 'Rathian', 'type': 'Flying Wyvern', 'size': 'large', 'locales': ['Ancient Forest', 'Wildspire Waste']},
{'name': 'Ruiner Nergigante', 'type': 'Elder Dragon', 'size': 'large', 'locales': []},
{'name': "Safi'jiiva", 'type': 'Elder Dragon', 'size': 'large', 'locales': []},
{'name': 'Savage Deviljho', 'type': 'Brute Wyvern', 'size': 'large', 'locales': []},
{'name': 'Scarred Yian Garuga', 'type': 'Bird Wyvern', 'size': 'large', 'locales': []},
{'name': 'Seething Bazelgeuse', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []},
{'name': 'Shara Ishvalda', 'type': 'Elder Dragon', 'size': 'large', 'locales': []},
{'name': 'Shrieking Legiana', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []},
{'name': 'Silver Rathalos', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []},
{'name': 'Stygian Zinogre', 'type': 'Fanged Wyvern', 'size': 'large', 'locales': []},
{'name': 'Teostra', 'type': 'Elder Dragon', 'size': 'large', 'locales': []},
{'name': 'Tigrex', 'type': 'Flying Wyvern', 'size': 'large', 'locales': []},
{'name': 'Tobi-Kadachi', 'type': 'Fanged Wyvern', 'size': 'large', 'locales': []},
{'name': 'Tziti-Ya-Ku', 'type': 'Bird Wyvern', 'size': 'large', 'locales': []},
{'name': 'Urugaan', 'type': 'Brute Wyvern', 'size': 'large', 'locales': []},
{'name': 'Vaal Hazak', 'type': 'Elder Dragon', 'size': 'large', 'locales': []},
{'name': 'Velkhana', 'type': 'Elder Dragon', 'size': 'large', 'locales': []},
{'name': 'Viper Tobi-Kadachi', 'type': 'Fanged Wyvern', 'size': 'large', 'locales': []},
{'name': 'Xenojiva', 'type': 'Elder Dragon', 'size': 'large', 'locales': []},
{'name': 'Yian Garuga', 'type': 'Bird Wyvern', 'size': 'large', 'locales': []},
{'name': 'Zinogre', 'type': 'Fanged Wyvern', 'size': 'large', 'locales': []},
{'name': 'Zorah Magdaros', 'type': 'Elder Dragon', 'size': 'large', 'locales': []},
]
