monsters = [
('Anteka', 'small'),
('Apceros', 'small'),
('Aptonoth', 'small'),
('Barnos', 'small'),
('Boaboa', 'small'),
('Cortos', 'small'),
('Gajalaka', 'small'),
('Gajau', 'small'),
('Gastodon', 'small'),
('Girros', 'small'),
('Grimalkyne', 'small'),
('Hornetaur', 'small'),
('Jagras', 'small'),
('Kelbi', 'small'),
('Kestodon', 'small'),
('Mernos', 'small'),
('Mosswine', 'small'),
('Noios', 'small'),
('Popo', 'small'),
('Raphinos', 'small'),
('Shamos', 'small'),
('Vespoid', 'small'),
('Wulg', 'small'),
('Acidic Glavenus', 'Brute Wyvern', 'large'),
('Alatreon', 'Elder Dragon', 'large'),
('Ancient Leshen', 'Relict', 'large'),
('Anjanath', 'Brute Wyvern', 'large'),
('Azure Rathalos', 'Flying Wyvern', 'large'),
('Banbaro', 'Brute Wyvern', 'large'),
('Barioth', 'Flying Wyvern', 'large'),
('Barroth', 'Brute Wyvern', 'large'),
('Bazelgeuse', 'Flying Wyvern', 'large'),
('Behemoth', 'Elder Dragon', 'large'),
('Beotodus', 'Piscine Wyvern', 'large'),
('Black Diablos', 'Flying Wyvern', 'large'),
('Blackveil Vaal Hazak', 'Elder Dragon', 'large'),
('Brachydios', 'Brute Wyvern', 'large'),
('Brute Tigrex', 'Flying Wyvern', 'large'),
('Coral Pukei-Pukei', 'Bird Wyvern', 'large'),
('Deviljho', 'Brute Wyvern', 'large'),
('Diablos', 'Flying Wyvern', 'large'),
('Dodogama', 'Fanged Wyvern', 'large'),
('Ebony Odogaron', 'Fanged Wyvern', 'large'),
('Fatalis', 'Elder Dragon', 'large'),
('Frostfang Barioth', 'Flying Wyvern', 'large'),
('Fulgar Anjanath', 'Brute Wyvern', 'large'),
('Furious Rajang', 'Fanged Beast', 'large'),
('Glavenus', 'large'),
('Gold Rathian', 'large'),
('Great Girros', 'large'),
('Great Jagras', 'large'),
('Jyuratodos', 'large'),
('Kirin', 'large'),
('Kulu-Ya-Ku', 'large'),
('Kulve Taroth', 'large'),
('Kushala Daora', 'large'),
('Lavasioth', 'large'),
('Legiana', 'large'),
('Leshen', 'large'),
('Lunastra', 'large'),
('Namielle', 'large'),
('Nargacuga', 'large'),
('Nergigante', 'large'),
('Nightshade Paolumu', 'large'),
('Odogaron', 'large'),
('Paolumu', 'large'),
('Pink Rathian', 'large'),
('Pukei-Pukei', 'large'),
('Radobaan', 'large'),
('Raging Brachydios', 'large'),
('Rajang', 'large'),
('Ratholos', 'large'),
('Rathian', 'large'),
('Ruiner Nergigante', 'large'),
('Safi\'jiiva', 'large'),
('Savage Deviljho', 'large'),
('Scarred Yian Garuga', 'large'),
('Seething Bazelgeuse', 'large'),
('Shara Ishvalda', 'large'),
('Shrieking Legiana', 'large'),
('Silver Rathalos', 'large'),
('Stygian Zinogre', 'large'),
('Teostra', 'large'),
('Tigrex', 'large'),
('Tobi-Kadachi', 'large'),
('Tziti-Ya-Ku', 'large'),
('Urugaan', 'large'),
('Vaal Hazak', 'large'),
('Velkhana', 'large'),
('Viper Tobi-Kadachi', 'large'),
('Xeno''jiva', 'large'),
('Yian Garuga', 'large'),
('Zinogre', 'large'),
('Zorah Magdaros', 'large')
]
